### ISSUE TITLE
_init_py

### ISSUE THREAD

**Issue by Yelena123** [rflynn/regroup#6]
Hello! I am trying to run an example in Mac Terminal. I've got the following error message:
$ echo -e 'Mississippi\nMissouri' | python regroup.py
Traceback (most recent call last):
  File "regroup.py", line 7, in <module>
    from regroup import DAWG, DAWGRelaxer
  File "/Users/yt/regroup/regroup/__init__.py", line 170
    yield from cls._flatten(v, path + k)
             ^
SyntaxError: invalid syntax
 Do you know how to fix this problem? Thank you very much!

**Comment by kritikagarg** [comment]
The error is thrown by a bit of code that'd only work on Python 3.3 or newer.

See [](https://github.com/benoitc/gunicorn/issues/788)

**Comment by kritikagarg** [comment]
The error is thrown by a bit of code that'd only work on Python 3.3 or newer.

See https://github.com/benoitc/gunicorn/issues/788
